#pragma once
#include <iostream>
//#include <Windows.h>
#include <utility>
#include <algorithm>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <sstream>
#include <codecvt>
#include <commdlg.h>
#include <string>
#include <memory>
#include <functional>
#include <string_view>
#include <TlHelp32.h>
#include <tchar.h>
#include <Psapi.h>
#include <search.h>
#include <iomanip>
#include <locale>
#include <codecvt>
#include <any>
#include <variant>